### ISSUE TITLE
Missing components

### ISSUE THREAD

**Issue by runxel** [grasshopper3d/GrasshopperDocsSite#3]
Why are suddenly so many components missing?
Eg. `Replace Path`, `Split Tree`, `Path Compare` and others?

**Comment by robinrodricks** [comment]
Are you talking about the grasshopper components or any add-on in specific?

Any change is because the indexing algorithms were rewritten from scratch.

**Comment by runxel** [comment]
If I go to to rhino.github.io those components are missing.
They are all default components which belong to `Sets > Tree`.
Since also their icons are physically missing in this repo I assume this is kind of a regression/bug (?).

**Comment by robinrodricks** [comment]
Thanks for finding this out. We will check it out and let you know. It's
not a regression, like I said, the indexing has been rewritten from scratch
and there may be differences in behavior. Icons and pages were recreated
from scratch too. Older icons were deleted to prevent duplicates because
the naming scheme was also changed. I can try to copy the older naming
scheme so that inbound Google links are not broken.

**Comment by philipbelesky** [comment]
Hey, thanks for looking into this. I also noticed that a number on inbuilt components also seem to have been missing. For instance, it was previously possible to link to the `Panel` component but this is no longer the case.

**Comment by robinrodricks** [comment]
Sorted. Added:

- Clean Tree
- Cluster
- Curvature Graph
- Example
- Explode Tree
- Flatten Tree
- Gradient
- Graft Tree
- Group
- Null Check
- Legend
- Match Tree
- Merge Group
- MetaBall
- MetaBall(t)
- MetaBall(t) Custom
- Path Compare
- Prune Tree
- Read File
- Replace Paths
- Shift Paths
- Simplify Tree
- Smooth Numbers
- Split Group
- Stream Filter
- Stream Gate
- Text Tag 3D
- Text Tag 3D
- Text Tag
- Text Tag
- Split Tree
- Trim Tree
- Unflatten Tree
- Ungroup
- Timeline
